const relics = [
    {
        name: "Path of Gelid Wind",
        type: ["Hunter of Glacial Frost", "Eagle of Twilight Line"], 
        head: ["Hunter's Artaius Hood", "Eagle's Beaked Helmet"],
        hand: ["Hunter's Lizard Gloves", "Eagle's Soaring Ring"],
        body: ["Hunter's Ice Dragon Cloak", "Eagle's Winged Suit Harness"],
        feet: ["Hunter's Soft Elkskin Boots", "Eagle's Quilted Puttees"],
    },
    {
        name: "Path of Jabbing Punch",
        type: ["Champion of Streetwise Boxing", "Thief of Shooting Meteor"],
        head: ["Champion's Headgear", "Thief's Myriad Faced Mask"],
        hand: ["Champion's Heavy Gloves", "Thief's Gloves With Prints"],
        body: ["Champion's Chest Guard", "Thief's Steel Grappling Hook"], 
        feet: ["Champion's Fleetfoot Boots", "Thief's Meteor Boots"],
    }, 
    {
        name: "Path of Drifting",
        type: ["Passerby of Wandering Cloud", "Musketeer of Wild Wheat"],
        head: ["Passerby's Rejuvenated Wooden Hairstick", "Musketeer's Wild Wheat Felt Hat"],
        hand: ["Passerby's Roaming Dragon Bracer", "Musketeer's Coarse Leather Gloves"],
        body: ["Passerby's Ragged Embroided Coat", "Musketeer's Wind-Hunting Shawl"], 
        feet: ["Passerby's Stygian Hiking Boots", "Musketeer's Rivets Riding Boots"],
    },
    {
        name: "Path of Providence",
        type: ["Guard of Wuthering Snow", "Genius of Brilliant Stars"],
        head: [],
        hand: [],
        body: [], 
        feet: [],
    },
    {
        name: "Path of Holy Hymn",
        type: ["Knight of Purity Palace", "Band of Sizzling Thunder"],
        head: [],
        hand: [],
        body: [], 
        feet: [],
    },
    {
        name: "Path of Conflagration",
        type: ["Firesmith of Lava-Forging", "Wastelander of Banditry Desert"],
        head: [],
        hand: [],
        body: [], 
        feet: [],
    },
    {
        name: "Path of Elixir Seekers",
        type: ["Longevous Disciple", "Messenger Traversing Hackerspace"],
        head: [],
        hand: [],
        body: [], 
        feet: [],
    },
    {
        name: "Path of Darkness",
        type: ["The Ashblazing Grand Duke", "Prisoner in Deep Confinement"],
        head: [],
        hand: [],
        body: [], 
        feet: [],
    },
    {
        name: "Path of Dreamdive",
        type: ["Pioneer of Dead River Waters", "Master of Dream Machinations"],
        head: [],
        hand: [],
        body: [], 
        feet: [],
    }
]