const acheron = [
    {
        entitytype: "Character", 
        name: "Words Of Yore", 
        limited: "Acheron", 
        limitedimg: "https://hsr.honeyhunterworld.com/img/character/acheron-character_cut_in_front.webp?x76329",
        limitedtype: "(Lightning: Nihility)",
        loss: ["Himeko", "Welt", "Bailu", "Bronya", "Gepard", "Yanqing", "Clara"],
        lossimg: ["https://hsr.honeyhunterworld.com/img/character/himeko-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/welt-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/bailu-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/bronya-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/gepard-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/yanqing-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/clara-character_cut_in_front.webp?x76329"],
        rateup: ["Gallagher", "Pela", "Dan Heng"],
        rateupimg: ["https://hsr.honeyhunterworld.com/img/character/gallagher-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/pela-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/dan-heng-character_cut_in_front.webp?x76329"],
        rateuptype: ["(Abundence: Fire)", "(Nihility: Ice)", "(The Hunt: Wind)"],
        fourstarchara: ["Arlan", "Asta", "Guinaifen", "Hanya", "Herta", "Hook", "Luka", "Lynx", "March 7th", "Misha", "Natasha", "Qingque", "Sampo", "Serval", "Sushang", "Tingyun", "Xueyi", "Yukong",],
        fourstarcharaimg: ["https://hsr.honeyhunterworld.com/img/character/arlan-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/asta-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/guinaifen-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/hanya-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/herta-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/hook-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/luka-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/lynx-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/march-7th-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/misha-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/natasha-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/qingque-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/sampo-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/serval-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/sushang-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/tingyun-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/xueyi-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/yukong-character_cut_in_front.webp?x76329"], 
        fourstarlc: ["Post-Op Conversation", "Good Night and Sleep Well", "Day One of My New Life", "Only Silence Remains", "Memories of the Past", "The Moles Welcome You", "The Birth of the Self", "Shared Feeling", "Eyes of the Prey", "Landau's Choice", "Swordplay", "Planetary Rendezvous", "A Secret Vow", "Make the World Clamour", "Perfect Timing", "Resolution Shines as Pearls of Sweat", "Trend of the Universal Market", "Subscribe for More!", "Dance! Dance! Dance!", "Under the Blue Sky", "Geniuses' Repose", "Indelble Promise",],
        fourstarlcimg: ["https://starrail.honeyhunterworld.com/img/item/post-op-conversation-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/good-night-and-sleep-well-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/day-one-of-my-new-life-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/only-silence-remains-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/memories-of-the-past-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/the-moles-welcome-you-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/the-birth-of-the-self-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/shared-feeling-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/eyes-of-the-prey-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/landaus-choice-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/swordplay-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/planetary-rendezvous-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/a-secret-vow-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/make-the-world-clamor-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/perfect-timing-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/resolution-shines-as-pearls-of-sweat-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/trend-of-the-universal-market-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/subscribe-for-more-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/dance-dance-dance-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/under-the-blue-sky-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/geniuses-repose-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/indelible-promise-item_icon_thumbnail_medium.webp?x45311"], 
        threestars: ["Arrows", "Cornucopia", "Collapsing Sky", "Amber", "Void", "Chorus", "Data Bank", "Darting Arrow", "Fine Fruit", "Shattered Home", "Defense", "Loop", "Meshing Cogs", "Passkey", "Adversarial", "Multiplication", "Mutual Demise", "Pioneering", "Hidden Shadow", "Meditation", "Sagacity"], 
        threestarimg: ["https://hsr.honeyhunterworld.com/img/item/arrows-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/cornucopia-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/collapsing-sky-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/amber-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/void-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/chorus-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/data-bank-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/darting-arrow-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/fine-fruit-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/shattered-home-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/defense-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/loop-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/meshing-cogs-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/passkey-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/adversarial-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/multiplication-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/mutual-demise-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/pioneering-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/hidden-shadow-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/mediation-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/sagacity-item_icon_thumbnail_medium.webp?x92359"]
    }
]
const luocha = [

    {
        entitytype: "Character", 
        name: "Laic Pursuit", 
        limited: "Luocha", 
        limitedimg: "https://hsr.honeyhunterworld.com/img/character/luocha-character_cut_in_front.webp?x76329",
        limitedtype: "(Abundence: Imaginary)",
        loss: ["Himeko", "Welt", "Bailu", "Bronya", "Gepard", "Yanqing", "Clara"],
        lossimg: ["https://hsr.honeyhunterworld.com/img/character/himeko-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/welt-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/bailu-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/bronya-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/gepard-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/yanqing-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/clara-character_cut_in_front.webp?x76329"],
        rateup: ["Gallagher", "Pela", "Dan Heng"],
        rateupimg: ["https://hsr.honeyhunterworld.com/img/character/gallagher-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/pela-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/dan-heng-character_cut_in_front.webp?x76329"],
        rateuptype: ["(Abundence: Fire)", "(Nihility: Ice)", "(The Hunt: Wind)"],
        fourstarchara: ["Arlan", "Asta", "Guinaifen", "Hanya", "Herta", "Hook", "Luka", "Lynx", "March 7th", "Misha", "Natasha", "Qingque", "Sampo", "Serval", "Sushang", "Tingyun", "Xueyi", "Yukong",],
        fourstarcharaimg: ["https://hsr.honeyhunterworld.com/img/character/arlan-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/asta-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/guinaifen-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/hanya-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/herta-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/hook-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/luka-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/lynx-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/march-7th-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/misha-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/natasha-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/qingque-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/sampo-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/serval-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/sushang-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/tingyun-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/xueyi-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/yukong-character_cut_in_front.webp?x76329"], 
        fourstarlc: ["Post-Op Conversation", "Good Night and Sleep Well", "Day One of My New Life", "Only Silence Remains", "Memories of the Past", "The Moles Welcome You", "The Birth of the Self", "Shared Feeling", "Eyes of the Prey", "Landau's Choice", "Swordplay", "Planetary Rendezvous", "A Secret Vow", "Make the World Clamour", "Perfect Timing", "Resolution Shines as Pearls of Sweat", "Trend of the Universal Market", "Subscribe for More!", "Dance! Dance! Dance!", "Under the Blue Sky", "Geniuses' Repose", "Indelble Promise",],
        fourstarlcimg: ["https://starrail.honeyhunterworld.com/img/item/post-op-conversation-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/good-night-and-sleep-well-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/day-one-of-my-new-life-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/only-silence-remains-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/memories-of-the-past-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/the-moles-welcome-you-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/the-birth-of-the-self-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/shared-feeling-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/eyes-of-the-prey-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/landaus-choice-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/swordplay-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/planetary-rendezvous-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/a-secret-vow-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/make-the-world-clamor-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/perfect-timing-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/resolution-shines-as-pearls-of-sweat-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/trend-of-the-universal-market-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/subscribe-for-more-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/dance-dance-dance-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/under-the-blue-sky-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/geniuses-repose-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/indelible-promise-item_icon_thumbnail_medium.webp?x45311"], 
        threestars: ["Arrows", "Cornucopia", "Collapsing Sky", "Amber", "Void", "Chorus", "Data Bank", "Darting Arrow", "Fine Fruit", "Shattered Home", "Defense", "Loop", "Meshing Cogs", "Passkey", "Adversarial", "Multiplication", "Mutual Demise", "Pioneering", "Hidden Shadow", "Meditation", "Sagacity"], 
        threestarimg: ["https://hsr.honeyhunterworld.com/img/item/arrows-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/cornucopia-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/collapsing-sky-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/amber-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/void-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/chorus-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/data-bank-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/darting-arrow-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/fine-fruit-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/shattered-home-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/defense-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/loop-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/meshing-cogs-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/passkey-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/adversarial-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/multiplication-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/mutual-demise-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/pioneering-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/hidden-shadow-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/mediation-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/sagacity-item_icon_thumbnail_medium.webp?x92359"]
    },
]

const LC1 = [
    {
        entitytype: "Lightcone",
        name: "Brilliant Fixation", 
        limited: "Along the Passing Shore", 
        limitedimg: "https://hsr.honeyhunterworld.com/img/item/along-the-passing-shore-item_icon_thumbnail_medium.webp?x76329",
        limitedtype: "Nihility",
        loss: ["But the Battle Isn't Over", "In the Name of the World", "Moment of Victory", "Night on the Milky Way", "Sleep Like the Dead", "Something Irreplaceable", "Time Waits for No One"],
        lossimg: ["https://hsr.honeyhunterworld.com/img/item/but-the-battle-isnt-over-item_icon_thumbnail_medium.webp?x76329", "https://hsr.honeyhunterworld.com/img/item/in-the-name-of-the-world-item_icon_thumbnail_medium.webp?x76329", "https://hsr.honeyhunterworld.com/img/item/moment-of-victory-item_icon_thumbnail_medium.webp?x76329", "https://hsr.honeyhunterworld.com/img/item/night-on-the-milky-way-item_icon_thumbnail_medium.webp?x76329", "https://hsr.honeyhunterworld.com/img/item/sleep-like-the-dead-item_icon_thumbnail_medium.webp?x76329", "https://hsr.honeyhunterworld.com/img/item/something-irreplaceable-item_icon_thumbnail_medium.webp?x76329", "https://hsr.honeyhunterworld.com/img/item/time-waits-for-no-one-item_icon_thumbnail_medium.webp?x76329"],
        rateup: ["Good Night and Sleep Well", "Post-Op Conversation", "Subscribe for More!"], 
        rateupimg: ["https://hsr.honeyhunterworld.com/img/item/good-night-and-sleep-well-item_icon_thumbnail_medium.webp?x76329", "https://hsr.honeyhunterworld.com/img/item/post-op-conversation-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/subscribe-for-more-item_icon_thumbnail_medium.webp?x92359"],
        rateuptype: ["Nihility", "Abundence", "The Hunt"],
        fourstarchara: ["Arlan", "Asta", "Guinaifen", "Hanya", "Herta", "Hook", "Luka", "Lynx", "March 7th", "Misha", "Natasha", "Qingque", "Sampo", "Serval", "Sushang", "Tingyun", "Xueyi", "Yukong","Gallagher", "Pela", "Dan Heng"],
        fourstarcharaimg: ["https://hsr.honeyhunterworld.com/img/character/arlan-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/asta-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/guinaifen-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/hanya-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/herta-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/hook-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/luka-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/lynx-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/march-7th-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/misha-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/natasha-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/qingque-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/sampo-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/serval-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/sushang-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/tingyun-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/xueyi-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/yukong-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/gallagher-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/pela-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/dan-heng-character_cut_in_front.webp?x76329"], 
        fourstarlc: ["Post-Op Conversation", "Good Night and Sleep Well", "Day One of My New Life", "Only Silence Remains", "Memories of the Past", "The Moles Welcome You", "The Birth of the Self", "Shared Feeling", "Eyes of the Prey", "Landau's Choice", "Swordplay", "Planetary Rendezvous", "A Secret Vow", "Make the World Clamour", "Perfect Timing", "Resolution Shines as Pearls of Sweat", "Trend of the Universal Market", "Subscribe for More!", "Dance! Dance! Dance!", "Under the Blue Sky", "Geniuses' Repose", "Indelble Promise",],
        fourstarlcimg: ["https://starrail.honeyhunterworld.com/img/item/post-op-conversation-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/good-night-and-sleep-well-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/day-one-of-my-new-life-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/only-silence-remains-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/memories-of-the-past-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/the-moles-welcome-you-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/the-birth-of-the-self-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/shared-feeling-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/eyes-of-the-prey-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/landaus-choice-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/swordplay-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/planetary-rendezvous-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/a-secret-vow-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/make-the-world-clamor-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/perfect-timing-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/resolution-shines-as-pearls-of-sweat-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/trend-of-the-universal-market-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/subscribe-for-more-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/dance-dance-dance-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/under-the-blue-sky-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/geniuses-repose-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/indelible-promise-item_icon_thumbnail_medium.webp?x45311"], 
        threestars: ["Arrows", "Cornucopia", "Collapsing Sky", "Amber", "Void", "Chorus", "Data Bank", "Darting Arrow", "Fine Fruit", "Shattered Home", "Defense", "Loop", "Meshing Cogs", "Passkey", "Adversarial", "Multiplication", "Mutual Demise", "Pioneering", "Hidden Shadow", "Meditation", "Sagacity"], 
        threestarimg: ["https://hsr.honeyhunterworld.com/img/item/arrows-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/cornucopia-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/collapsing-sky-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/amber-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/void-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/chorus-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/data-bank-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/darting-arrow-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/fine-fruit-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/shattered-home-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/defense-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/loop-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/meshing-cogs-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/passkey-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/adversarial-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/multiplication-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/mutual-demise-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/pioneering-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/hidden-shadow-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/mediation-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/sagacity-item_icon_thumbnail_medium.webp?x92359"]
    },
]

const LC2 = [
    {
        entitytype: "Lightcone", 
        name: "Bygone Reminiscence", 
        limited: "Echoes of the Coffin",
        limitedimg: "https://hsr.honeyhunterworld.com/img/item/echoes-of-the-coffin-item_icon_thumbnail_medium.webp?x92359",
        limitedtype: "Abundence",
        loss: ["But the Battle Isn't Over", "In the Name of the World", "Moment of Victory", "Night on the Milky Way", "Sleep Like the Dead", "Something Irreplaceable", "Time Waits for No One"],
        lossimg: ["https://hsr.honeyhunterworld.com/img/item/but-the-battle-isnt-over-item_icon_thumbnail_medium.webp?x76329", "https://hsr.honeyhunterworld.com/img/item/in-the-name-of-the-world-item_icon_thumbnail_medium.webp?x76329", "https://hsr.honeyhunterworld.com/img/item/moment-of-victory-item_icon_thumbnail_medium.webp?x76329", "https://hsr.honeyhunterworld.com/img/item/night-on-the-milky-way-item_icon_thumbnail_medium.webp?x76329", "https://hsr.honeyhunterworld.com/img/item/sleep-like-the-dead-item_icon_thumbnail_medium.webp?x76329", "https://hsr.honeyhunterworld.com/img/item/something-irreplaceable-item_icon_thumbnail_medium.webp?x76329", "https://hsr.honeyhunterworld.com/img/item/time-waits-for-no-one-item_icon_thumbnail_medium.webp?x76329"],
        rateup: ["Good Night and Sleep Well", "Post-Op Conversation", "Subscribe for More!"], 
        rateupimg: ["https://hsr.honeyhunterworld.com/img/item/good-night-and-sleep-well-item_icon_thumbnail_medium.webp?x76329", "https://hsr.honeyhunterworld.com/img/item/post-op-conversation-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/subscribe-for-more-item_icon_thumbnail_medium.webp?x92359"],
        rateuptype: ["Nihility", "Abundence", "The Hunt"],
        fourstarchara: ["Arlan", "Asta", "Guinaifen", "Hanya", "Herta", "Hook", "Luka", "Lynx", "March 7th", "Misha", "Natasha", "Qingque", "Sampo", "Serval", "Sushang", "Tingyun", "Xueyi", "Yukong","Gallagher", "Pela", "Dan Heng"],
        fourstarcharaimg: ["https://hsr.honeyhunterworld.com/img/character/arlan-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/asta-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/guinaifen-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/hanya-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/herta-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/hook-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/luka-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/lynx-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/march-7th-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/misha-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/natasha-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/qingque-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/sampo-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/serval-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/sushang-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/tingyun-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/xueyi-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/yukong-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/gallagher-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/pela-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/dan-heng-character_cut_in_front.webp?x76329"], 
        fourstarlc: ["Post-Op Conversation", "Good Night and Sleep Well", "Day One of My New Life", "Only Silence Remains", "Memories of the Past", "The Moles Welcome You", "The Birth of the Self", "Shared Feeling", "Eyes of the Prey", "Landau's Choice", "Swordplay", "Planetary Rendezvous", "A Secret Vow", "Make the World Clamour", "Perfect Timing", "Resolution Shines as Pearls of Sweat", "Trend of the Universal Market", "Subscribe for More!", "Dance! Dance! Dance!", "Under the Blue Sky", "Geniuses' Repose", "Indelble Promise",],
        fourstarlcimg: ["https://starrail.honeyhunterworld.com/img/item/post-op-conversation-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/good-night-and-sleep-well-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/day-one-of-my-new-life-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/only-silence-remains-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/memories-of-the-past-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/the-moles-welcome-you-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/the-birth-of-the-self-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/shared-feeling-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/eyes-of-the-prey-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/landaus-choice-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/swordplay-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/planetary-rendezvous-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/a-secret-vow-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/make-the-world-clamor-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/perfect-timing-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/resolution-shines-as-pearls-of-sweat-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/trend-of-the-universal-market-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/subscribe-for-more-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/dance-dance-dance-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/under-the-blue-sky-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/geniuses-repose-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/indelible-promise-item_icon_thumbnail_medium.webp?x45311"], 
        threestars: ["Arrows", "Cornucopia", "Collapsing Sky", "Amber", "Void", "Chorus", "Data Bank", "Darting Arrow", "Fine Fruit", "Shattered Home", "Defense", "Loop", "Meshing Cogs", "Passkey", "Adversarial", "Multiplication", "Mutual Demise", "Pioneering", "Hidden Shadow", "Meditation", "Sagacity"], 
        threestarimg: ["https://hsr.honeyhunterworld.com/img/item/arrows-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/cornucopia-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/collapsing-sky-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/amber-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/void-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/chorus-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/data-bank-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/darting-arrow-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/fine-fruit-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/shattered-home-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/defense-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/loop-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/meshing-cogs-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/passkey-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/adversarial-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/multiplication-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/mutual-demise-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/pioneering-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/hidden-shadow-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/mediation-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/sagacity-item_icon_thumbnail_medium.webp?x92359"]
    }, 
]

const standard = [
    {
        entitytype: "Standard", 
        name: "Stellar Warp", 
        limited: ["Himeko", "Welt", "Bailu", "Bronya", "Gepard", "Yanqing", "Clara"],
        limitedimg: ["https://hsr.honeyhunterworld.com/img/character/himeko-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/welt-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/bailu-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/bronya-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/gepard-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/yanqing-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/clara-character_cut_in_front.webp?x76329"],
        limitedtype: ["(Erudition: Fire)", "(Nihility: Imaginary", "(Abundence: Lightning)", "(Harmony: Wind)", "(Preservation: Ice)", "(The Hunt: Ice)", "(Destruction: Physical)"],
        loss: ["But the Battle Isn't Over", "In the Name of the World", "Moment of Victory", "Night on the Milky Way", "Sleep Like the Dead", "Something Irreplaceable", "Time Waits for No One"],
        lossimg: ["https://hsr.honeyhunterworld.com/img/item/but-the-battle-isnt-over-item_icon_thumbnail_medium.webp?x76329", "https://hsr.honeyhunterworld.com/img/item/in-the-name-of-the-world-item_icon_thumbnail_medium.webp?x76329", "https://hsr.honeyhunterworld.com/img/item/moment-of-victory-item_icon_thumbnail_medium.webp?x76329", "https://hsr.honeyhunterworld.com/img/item/night-on-the-milky-way-item_icon_thumbnail_medium.webp?x76329", "https://hsr.honeyhunterworld.com/img/item/sleep-like-the-dead-item_icon_thumbnail_medium.webp?x76329", "https://hsr.honeyhunterworld.com/img/item/something-irreplaceable-item_icon_thumbnail_medium.webp?x76329", "https://hsr.honeyhunterworld.com/img/item/time-waits-for-no-one-item_icon_thumbnail_medium.webp?x76329"],
        rateup: null, 
        rateupimg: null, 
        fourstarchara: ["Arlan", "Asta", "Guinaifen", "Hanya", "Herta", "Hook", "Luka", "Lynx", "March 7th", "Misha", "Natasha", "Qingque", "Sampo", "Serval", "Sushang", "Tingyun", "Xueyi", "Yukong","Gallagher", "Pela", "Dan Heng"],
        fourstarcharaimg: ["https://hsr.honeyhunterworld.com/img/character/arlan-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/asta-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/guinaifen-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/hanya-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/herta-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/hook-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/luka-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/lynx-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/march-7th-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/misha-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/natasha-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/qingque-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/sampo-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/serval-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/sushang-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/tingyun-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/xueyi-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/yukong-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/gallagher-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/pela-character_cut_in_front.webp?x76329", "https://hsr.honeyhunterworld.com/img/character/dan-heng-character_cut_in_front.webp?x76329"], 
        fourstarlc: ["Post-Op Conversation", "Good Night and Sleep Well", "Day One of My New Life", "Only Silence Remains", "Memories of the Past", "The Moles Welcome You", "The Birth of the Self", "Shared Feeling", "Eyes of the Prey", "Landau's Choice", "Swordplay", "Planetary Rendezvous", "A Secret Vow", "Make the World Clamour", "Perfect Timing", "Resolution Shines as Pearls of Sweat", "Trend of the Universal Market", "Subscribe for More!", "Dance! Dance! Dance!", "Under the Blue Sky", "Geniuses' Repose", "Indelble Promise",],
        fourstarlcimg: ["https://starrail.honeyhunterworld.com/img/item/post-op-conversation-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/good-night-and-sleep-well-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/day-one-of-my-new-life-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/only-silence-remains-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/memories-of-the-past-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/the-moles-welcome-you-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/the-birth-of-the-self-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/shared-feeling-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/eyes-of-the-prey-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/landaus-choice-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/swordplay-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/planetary-rendezvous-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/a-secret-vow-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/make-the-world-clamor-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/perfect-timing-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/resolution-shines-as-pearls-of-sweat-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/trend-of-the-universal-market-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/subscribe-for-more-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/dance-dance-dance-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/under-the-blue-sky-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/geniuses-repose-item_icon_thumbnail_medium.webp?x45311", "https://starrail.honeyhunterworld.com/img/item/indelible-promise-item_icon_thumbnail_medium.webp?x45311"], 
        threestars: ["Arrows", "Cornucopia", "Collapsing Sky", "Amber", "Void", "Chorus", "Data Bank", "Darting Arrow", "Fine Fruit", "Shattered Home", "Defense", "Loop", "Meshing Cogs", "Passkey", "Adversarial", "Multiplication", "Mutual Demise", "Pioneering", "Hidden Shadow", "Meditation", "Sagacity"], 
        threestarimg: ["https://hsr.honeyhunterworld.com/img/item/arrows-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/cornucopia-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/collapsing-sky-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/amber-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/void-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/chorus-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/data-bank-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/darting-arrow-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/fine-fruit-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/shattered-home-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/defense-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/loop-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/meshing-cogs-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/passkey-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/adversarial-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/multiplication-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/mutual-demise-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/pioneering-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/hidden-shadow-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/mediation-item_icon_thumbnail_medium.webp?x92359", "https://hsr.honeyhunterworld.com/img/item/sagacity-item_icon_thumbnail_medium.webp?x92359"]
    }
]

export {acheron, luocha, LC1, LC2, standard}